# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-r-package:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
#          - {os: macOS-latest,   r: 'devel'}
#          - {os: macOS-latest,   r: 'oldrel-1'}
          - {os: windows-latest, r: 'release'}
#          - {os: windows-latest, r: 'devel'}
#          - {os: windows-latest, r: 'oldrel-1'}
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}
    runs-on: ${{ matrix.config.os }}
    name: check-r-package on ${{ matrix.config.os }} using R version ${{ matrix.config.r }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
  styler-lintr-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Check style
        run: styler::style_pkg(dry = "fail")
        shell: Rscript {0}
      - name: Check lints
        run: library(magrittr); lintr::lint_package()
        shell: Rscript {0}
        # TODO: ^ fail if lintr has warnings
      - name: Check spelling
        run: spelling::spell_check_package()
        shell: Rscript {0}
        # TODO: ^ fail if spelling has errors
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
        shell: Rscript {0}
        # TODO: ^ fail if coverage is lower than high water mark
  pkgdown:
    runs-on: ubuntu-latest
    needs: [check-r-package, styler-lintr-spelling, coverage]
    if: ${{ github.ref_name == 'main' }} # Only on push to main
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build and deploy site
        run: pkgdown::build_site_github_pages()
        shell: Rscript {0}
