# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  setup:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macOS-latest,   r: 'release'}
#          - {os: macOS-latest,   r: 'devel'}
#          - {os: macOS-latest,   r: 'oldrel-1'}
#          - {os: windows-latest, r: 'release'}
#          - {os: windows-latest, r: 'devel'}
#          - {os: windows-latest, r: 'oldrel-1'}
#          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
#          - {os: ubuntu-latest,  r: 'oldrel-1'}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
  check-r-package:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    needs: [setup]
    steps:
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
  styler:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Check style
        run: styler::style_pkg(dry = "fail")
        shell: Rscript {0}
  lintr:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Check lints
        run: lintr::lint_package()
        shell: Rscript {0}
  spelling:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Check spelling
        run: spelling::spell_check_package(pkg)
        shell: Rscript {0}
#      - name: Test coverage
#        run: |
#          cov <- covr::package_coverage(
#            quiet = FALSE,
#            clean = FALSE,
#            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
#          )
#          print(cov)
#        shell: Rscript {0}
  pkgdown:
    runs-on: ubuntu-latest
    needs: [check-r-package, lintr, styler, spelling]
    if: ${{ github.ref_name == 'main' }} # Only on push to main
    steps:
      - name: Build and deploy site
        run: pkgdown::build_site_github_pages()
        shell: Rscript {0}
