# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macOS-latest,   r: 'release'}
#          - {os: macOS-latest,   r: 'devel'}
#          - {os: macOS-latest,   r: 'oldrel-1'}
#          - {os: windows-latest, r: 'release'}
#          - {os: windows-latest, r: 'devel'}
#          - {os: windows-latest, r: 'oldrel-1'}
#          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
#          - {os: ubuntu-latest,  r: 'oldrel-1'}

    # env:
      # GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
            any::lintr
            any::styler
            any::spelling
          needs: check

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}

      - name: Style
        run: styler::style_pkg(dry = "fail")
        shell: Rscript {0}

      - name: Spell check
        run: |
          pkg_name <- pkgload::pkg_name()
          # add common, non-English words to a temporary dictionary
          dict_file <- tempfile()
          writeLines(c("uRbano", "raster", "terra", "sf", "rgb"), dict_file)
          spelling::spell_check_files(
            list.files(
              c("R", "vignettes"),
              pattern = "\\.(R|Rmd)$",
              full.names = TRUE,
              recursive = TRUE
            ),
            ignore = spelling::get_wordlist(
              pkg = file.path(pkg_name),
              vignettes = TRUE,
              wordlist = dict_file
            )
          )
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
